name: compress

on:
#   push:
#     branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Test
        run: |
          git stat
          git log
          git log --pretty=format:"" --name-status -1 | grep '^A(jpg\|png\|gif\|ico)' | awk '{print $2}'
          git log --pretty=format:"" --name-status -1 | grep '^M(jpg\|png\|gif\|ico)' | awk '{print $2}'
      
#         # 安装 node.js
#       - name: Install node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14
#           check-latest: true
      
#       - name: Install super-tinypng
#         run: npm i super-tinypng -g

#       - name: Run compress
#         run: sudo bash tinypng.sh
        
#       - name: Git auto commit
#         uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_message: Compress by tiny-png
#           add_options: '-A'
